- 异常匹配 p275

  抛出异常的时候，异常处理程序会按照代码的书写顺序找出最近的处理程序

  查找的时候并不要求跑出的异常同处理程序所声明的异常完全匹配，**派生类对象也可以匹配其基类的处理程序**

  但有一点要注意的是，不要把捕获基类的catch子句放在最前面，这样会把派生类的异常给屏蔽掉

  ```java
  Base extends Exception {}
  Sub extends Base {}
  ```

  ```java
  try {
      
  } catch(Base a) {
      
  } catch(Sub s) { //这样会报错，因为Base屏蔽了Sub的错误处理
      
  }
  ```

- 异常处理的重要原则 p276

  1. 只有在知道如何处理的情况下才捕获异常

  异常处理的另一个重要目标：

  把错误处理的代码同错误发生的地点相分离

- 异常处理中的"吞食"问题 p276

  ```java
  try {
      ...
  } catch(Exception e) {
      //什么也不做
  }
  ```

  上述代码虽然可以通过编译，但是除非记得复查并改正代码，否则异常将会丢失

- 将异常传给控制台 p279

  ```java
  public class MainException {
    // Pass all exceptions to the console:
    public static void main(String[] args) throws Exception {
      // Open the file:
      FileInputStream file =
        new FileInputStream("MainException.java");
      // Use the file ...
      // Close the file:
      file.close();
    }
  }
  ```

  可以从main()传递给控制台，main()也可以有异常说明

- 把"被检查的异常"转化为"不检查的异常" p279

  可以将异常包装进`RuntimeException`里面，如下所示

  ```java
  try {
      
  } catch(IDontKnowWhatToDoWithThisCheckedException e) {
      throw new RuntimeException(e);
  }
  ```

  在运用上述方法之后，还可以使用`getCause()`捕获并处理特定的异常

  ```java
  class TestException extends Exception {}
  
  class WrapCheckedException {
    void throwRuntimeException(int type) {
      try {
        switch(type) {
          case 0: throw new FileNotFoundException();
          case 1: throw new IOException();
          case 2: throw new RuntimeException("Where am I?");
          default: return;
        }
      } catch(Exception e) { // Adapt to unchecked:
        throw new RuntimeException(e);
      }
    }
  }
  
  class SomeOtherException extends Exception {}
  
  public class TurnOffChecking {
    public static void main(String[] args) {
      WrapCheckedException wce = new WrapCheckedException();
      // You can call throwRuntimeException() without a try
      // block, and let RuntimeExceptions leave the method:
      wce.throwRuntimeException(3);
      // Or you can choose to catch exceptions:
      for(int i = 0; i < 4; i++)
        try {
          if(i < 3)
            wce.throwRuntimeException(i);
          else
            throw new SomeOtherException();
        } catch(SomeOtherException e) {
            print("SomeOtherException: " + e);
        } catch(RuntimeException re) {
          try {
            throw re.getCause(); //这里使用了throw
          } catch(FileNotFoundException e) {
            print("FileNotFoundException: " + e);
          } catch(IOException e) {
            print("IOException: " + e);
          } catch(Throwable e) {
            print("Throwable: " + e);
          }
        }
    }
  } /* Output:
  FileNotFoundException: java.io.FileNotFoundException
  IOException: java.io.IOException
  Throwable: java.lang.RuntimeException: Where am I?
  SomeOtherException: SomeOtherException
  *///:~
  ```

- 构造函数是静态方法 p96

- 类初始化的时候先初始静态数据，之后是非静态数据，再之后是构造函数 p94

  > 在类的内部，变量定义的先后顺序决定了初始化的顺序。即使变量定义散布于方法定义之间，它们仍旧会在任何方法(包括构造器)调用之前得到初始化